name: Rust Build and Test

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: ouzi-dev/commit-status-updater@v2
      - if: always()
        uses: ouzi-dev/commit-status-updater@v2
        with:
          status: "${{ job.status }}"
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Run tests
        run: cargo test --release --verbose --lib
      - name: Run Ignored Test
        run: cargo test --release --verbose -- --ignored
      - name: Build
        run: cargo build --verbose --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: snip-${{ matrix.os }}
          path: |
            ./target/release/rsnippet${{ matrix.os == 'windows-latest' && '.exe' || '' }}
